init: git config --global core.autocrlf input
shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 4
  - npm install --production
  - npm install mocha should
build: off
test_script: npm run-script test-dot
cache: node_modules
